### ISSUE TITLE
module no longer compatible with react v16

### ISSUE THREAD

**Issue by natashache** [benwiley4000/react-responsive-audio-player#130]
@benwiley4000 The player stopped working after upgrading react to v16. Error says "can't read property 'bind' of undefined" at line 91. Any idea what's going on?

**Comment by benwiley4000** [comment]
@natashache thank you for flagging! I'll investigate shortly and follow up.

**Comment by benwiley4000** [comment]
@natashache I believe the issue is only that React 16 wasn't marked as a compatible version in the package.json, but the example.html page you can access by running `npm run dev` seems to work fine when I change the version numbers to 16. Could you checkout the `react-16` branch and verify if the example page works for you? If so I'll merge #131 to master.

**Comment by natashache** [comment]
@benwiley4000 Turned out it wasn't an issue with this module. I changed the webpack configuration setting after upgrading to react 16, which inadvertently overwrote the console object. Hence the error. It is working with no problem now. Sorry about the false alarm.

**Comment by benwiley4000** [comment]
@natashache thanks, and no problem! I needed to update the package anyway, so I appreciate the flag. Feel free to flag any other issues you run into.

**Comment by benwiley4000** [comment]
I released v1.1.5 which marks the package as compatible with React 16.
