### ISSUE TITLE
Does not play nice with react router / rc-menu

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [benwiley4000/react-responsive-audio-player#3]
I am using https://themeteorchef.com/base/ as the starting point. I replaced Bootstrap with material. 

The player works fine until you navigate at which point it resets. I'm not entirely sure what is conflicting but my best guess thus far is either react route or rc-menu. It seems the state of the player is updated each time you navigate. This can be seen in react dev tools. As I navigate via the menu you can see the activeTrackIndex being updated. The weird part is I have the player as a top level component. I am going to setup some test latter to try and narrow it down to either react router or rc-menu.

If you have any suggestion please let me know. Your player fits my requirements perfectly.

Here is the main App class so you can see how the player is used.

      import React from "react";
      import AppNavigation from "../containers/app-navigation";
      import { Footer } from "../components/footer/footer.jsx";
      //import { Player } from "../components/player/player";
      import AudioPlayer from "react-responsive-audio-player";
      import Container from "muicss/lib/react/container";
      
      var playlist =
      [{ url: "shows/testshow9/mpthreetest.mp3",
        displayText: "Track 3 by Some Artist" },
        { url: "shows/testshow9/mpthreetest.mp3",
          displayText: "Some Other Artist - Track 2" }];
  
    export class App extends React.Component {
      constructor(params) {
        super(params);
  
        // this.playlist =
        // [{ url: 'shows/testshow9/mpthreetest.mp3',
        //   displayText: 'Track 3 by Some Artist' },
        //   { url: 'shows/testshow9/mpthreetest.mp3',
        //     displayText: 'Some Other Artist - Track 2' }];
  
      }
  
      render() {
        return <div>
          <AppNavigation />
          <Container>
            { this.props.children }
          </Container>
          <Footer/>
          <AudioPlayer playlist={ playlist } />
        </div>;
      }
    }

**Comment by MichaelLeeHobbs** [comment]
The problem is when you 
   <Player playlist={playlist}/>

Each time you navigate it sends in a new prop causing the: componentWillReceiveProps to fire which resets the play list. I am working on a solution. Once I have it I will fork the project and then submit a merge request.

**Comment by benwiley4000** [comment]
@MichaelLeeHobbs thank you! I'll be happy to look over the PR and merge as long as it makes sense.

**Comment by MichaelLeeHobbs** [comment]
@benwiley4000 I ended up customizing the player.  I'm building a podcast website. Originally, I was passing a reference up from the component that holds the player and then back down into any component that would need access to it. This was cumbersome, so I put the player in the global context for now like so and removed the  componentWillReceiveProps.

    componentWillMount() {
      window.Player = {
        play: this.play.bind(this),
        addToPlayList: this.addToPlayList.bind(this),
        clearPlayList: this.clearPlayList.bind(this)
      };
    }
  
    play(value) {
      console.log("AudioPlayer.addToPlayList.value: ", value);
      if (!value.url || !value.displayText) {
        return;
      }
      this.playlist = [value];
      this.currentTrackIndex = -1;
      this.skipToNextTrack(true);
    }
  
  
    addToPlayList(value) {
      console.log("AudioPlayer.addToPlayList.value: ", value);
      if (!value.url || !value.displayText) {
        return;
      }
      this.playlist.push(value);
    }
  
    clearPlayList() {
      this.playlist = [];
      //this.togglePause(true);
      this.currentTrackIndex = -1;
      this.setState({
        activeTrackIndex: -1,
        displayedTime: 0
      }, () => {
        this.togglePause(true);
      });
    }

**Comment by benwiley4000** [comment]
@MichaelLeeHobbs alright - for future reference though, I would love a semi-thorough description of what you see to be the problem with the player's current implementation, so that I could make it better.

**Comment by benwiley4000** [comment]
If you have an example repo demonstrating the problem that would be ideal - perhaps you could direct to an earlier commit where you were experiencing said problem so I could take a look?

**Comment by benwiley4000** [comment]
I'm re-reading this thread and it makes sense to me now.

The simple solution to your problem is to check for playlist equality (`===`) in `componentWillReceiveProps`, and return if so.

This brings up a few other questions though -
1. Currently, if the new playlist prop is falsy, it gets ignored. This seems contrary to React principles, so perhaps that should result in the playlist stopping or fading out?
2. If we agreed on the playlist equality test, does that mean a playlist that is deeply equal but not equal-equal should reset the player? For example, what if your application triggers a new playlist async fetch and at the end the Redux builds a new copy of the same playlist? Should the default behavior be to reset?
3. Further, if we decide NO it should not reset, how about a playlist which is different but contains the song which is already playing? I wonder if we should preserve playback but change the index of the currently playing song to match its index in the new playlist.

Perhaps some config options should be available to change this behavior but I am leaning toward allowing continuous playback for new playlists as long as the current track is still in it.

**Comment by benwiley4000** [comment]
I decided to go ahead and make the changes I described. The original issue should be resolved, and the player should work better in general when swapping playlists. See https://github.com/benwiley4000/react-responsive-audio-player/pull/10.
